import { ensureDirectoryExistence, writeFile } from './util'
import { format } from '@prisma/prisma-fmt-wasm'
import { pathToFileURL } from 'url'
import { ParsedPrismaSchema } from './types'

export async function writeSchema(parsedSchema: ParsedPrismaSchema, outputPath: string, dry: boolean) {
  const header = [
    '//',
    `// Autogenerated by \`prisma-import\``,
    '// Any modifications will be overwritten on subsequent runs.',
    '//',
    '',
  ]

  const resultingSchema = format(
    [...header, parsedSchema.datasource, ...parsedSchema.generators, parsedSchema.content].join('\n'),
    JSON.stringify({
      textDocument: {
        uri: pathToFileURL(outputPath),
      },
      options: {
        tabSize: 2,
        insertSpaces: true,
      },
    }),
  )

  if (dry) {
    console.log(resultingSchema)
  } else {
    await ensureDirectoryExistence(outputPath)
    await writeFile(outputPath, resultingSchema)
  }
}
