name: Check for commits by Prisma team

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  check_commits:
    name: Check for commits by Prisma team
    runs-on: ubuntu-latest
    timeout-minutes: 7
    outputs:
      has_commits: ${{ steps.check.outputs.has_commits }}
      latest_commit: ${{ steps.latest.outputs.latest_commit }}
      pr_body: ${{ steps.pr_body.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Clone prisma/language-tools
        run: |
          git clone --branch=stable --shallow-since="2022-12-05T00:00:00Z" https://github.com/prisma/language-tools.git /tmp/language-tools
          cd /tmp/language-tools
          cp $GITHUB_WORKSPACE/scripts/check_for_commits.js ./scripts
          cp $GITHUB_WORKSPACE/scripts/versions/commit_sync ./scripts/versions
          npm install

      - name: Check for commits
        id: check
        run: |
          cd /tmp/language-tools
          node scripts/check_for_commits.js check

      - name: Set latest commit
        if: steps.check.outputs.has_commits == 'true'
        id: latest
        run: |
          cd /tmp/language-tools
          node scripts/check_for_commits.js last

      - name: Set PR body
        if: steps.check.outputs.has_commits == 'true'
        id: pr_body
        run: |
          cd /tmp/language-tools
          BODY=$(node scripts/check_for_commits.js)
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=content::$BODY"

  create_pr:
    name: Create a new Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 7
    needs: [check_commits]
    if: needs.check_commits.outputs.has_commits == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          sh scripts/set_git_credentials.sh

      - name: Check if PR already exists
        id: check
        run: |
          sh scripts/check_for_pr.sh sync/${{ needs.check_commits.outputs.latest_commit }}

      - name: Update latest commit
        if: steps.check.outputs.can_create_pr == 'true'
        run: |
          echo "${{ needs.check_commits.outputs.latest_commit }}" > scripts/versions/commit_sync

      - name: Create Pull Request
        if: steps.check.outputs.can_create_pr == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          title: '[sync] New commits in prisma/language-tools'
          body: ${{ needs.check_commits.outputs.pr_body }}
          commit-message: Update last commit sync to ${{ needs.check_commits.outputs.latest_commit }}
          branch: sync/${{ needs.check_commits.outputs.latest_commit }}
          delete-branch: true
